---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAOyPEA1c1crVtaUoxp4YN7TUGwwugnQ288w+g0dSend/I6ivlmDlP30pcPSQBu0zbBd5Oe/QREe66nJeIpGRIFCPB/i95fy0rrmRT2pKJbjNhYMhH5oR5SFGXzuNxglLNVsyTERvLWxLHNdOxwJlA/lfhpKdqJUTYdnKj8Vz9Z6+QYk+y6r4mBpKS4fDTajdahm7Kd21QELdQGfdN+qOfntAQWdLsctEHlrFJITbugXfqY1tJXzJrkWgikcwq+ZwuzWBhNFMKuxAVQt2Bz3J/S1C/C5vj5THQmlRooX2vd7GD65sERbS9n/w8vR/TTT1h0NGP2nFntvC5inkCxiMBsUL5kN0vFEPT460XA0yYdKXBAHm1h5ZSyBHBZqyGF5pKXsN3q66heN/zcbCYDf8FBRXAZ8UQu7AGFBizMZ9DGbtMkb5JR9QabDkwaSORK2HmP/9boEh6bSLUTBWc9/aOxtUmyzKTYVJZDtkjLTL1+m8W0W8zFTBST/QD1m0v5zNGtR8Md2fY1pTV/5WcLwxkyyKxkCKE2YPqxSl7K/xfIQvh6CFECVyuW/3gGoSQJxnSvLblCe5rMVcyxta9DX6cAA2lmlBSm8n7KWPFgBsOkcdhxBZVwRbH8SO3ElMHXiFyYrhAFru8x7JpVrQxb1L732Cv/fFMsEhn3/EXQV0JjB9mwLt43q/b8fk+vD9mC8at8mm4HFTdqFZpp6aFqwiqClj/A2mY/C536u3v1uK8IPDrYS4vZd1Ry3fWL452D5pnCkA0I7w==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
