---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBFk1IYU4MFJysCVgmcoqGRcikGLcRVw6H5qb9GGAlBMNZAc27WboGjKEN4RcACddFQAoV5bjvaGXA/oV3hfEbJpfkChoOMCpYu6Hp9bhgeMcNDtTSek0khDbNfskJMWcmnfjd3m9pCM0zagA1tbJKgb2M+2HSrfgHZf6IStMZVe+1nsixdH2n5Vkdz8jtOT0g6/Z+u/qkK1MnW7PcWvxhHfHQQX0GjCyAmaEP+c5Jcc0sIk6tBywcP87sU/FxqMLs7meeAli4Gv/XSyX6HHH5MMMofospSmf60QW+/FwTigXNOc5T+jf55boQWBJYjXa04epgKwr0kpWONBkRPnIg7D8irlkdSxoXE1tHdgDrVceI1b/xxDXae/FytxinlMWFUwe94mrdVh1qto1ftVjCRT5KEN+iN4GjVB/Xl4KQbuDDm8rRZ9EnW7VMFXp9+JtsodnKz+tUOA7nk1W3K5hujToQIkEo8h0haRvXkNs7UHUpSBIgzJszSsuC2JceMh1Nhr46kvKMb7D3hAoM6U0tchyD+1cB50OVhxnni3c5/6TCBY07Fx2E7Oh7j7P30RgKHo0yk7v5p3uxCImgS/m/IzYbCwyKNHaTzSnXUxoi8XwfqoaTyI0Q1NzFZyHd2db3p2QyWB71IKaSQ2ePqU6yd7E0+2Q2YPLIC+67PxA86trtpO2W5B7rryY6Xw1d3eFEEqPc6j+h64QoXGJsZcTCpQsz18wbcr/Nk93GLHl38F2BD1wAwNq6hO8Doe/il9xjDu/mIGQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
