# ai.perihelion.live -> odysseus on phis4:7000
---
apiVersion: v1
kind: Service
metadata:
  name: odysseus
  namespace: external
spec:
  ports:
    - port: 7000
      targetPort: 7000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: odysseus
  namespace: external
  labels:
    kubernetes.io/service-name: odysseus
addressType: IPv4
ports:
  - port: 7000
endpoints:
  - addresses: ["192.168.1.215"]
    conditions:
      ready: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: odysseus
  namespace: external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ai.perihelion.live`)
      kind: Rule
      services:
        - name: odysseus
          port: 7000
      middlewares:
        - name: web-security-headers
  tls: {}
