---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: victoriametrics-auth
  namespace: external
spec:
  encryptedData:
    users: AgCtElDsfpzymCYCu6M1kvosAjE+TvZkwRskQpgMn14F8vgWjZSLlpJ/rjlMeXTMIeBsGEbUKA3xLhpDWhHevJR5/wcmHmOmGHPtVqyy2WaKJlUqeHunnrlVA5KblrUvZ1CEICAV/10dqQnqUBMZuo+B/GH/6riGP/ecuMHpweve0KLPvccwa31wdEWcRHl8tiIcsuwm2VUY6nLEyKY8l6MJJZHBi0LvxPGLnha0or8BkTykGY4vKioXQtqBkUxVDx5DDgrx6JFFaZLCmtjrIA0ZCaag26ToHNAa0PqXEb4aDmx1DrtbBUWI4rnNFAIk2ziGxjyFU9u+VY7m0yd2mH/79k1iqX2jbaJFhxFY9xN0z/ZYDLDZm1HVCl4Rw8hF/VoQ/uEevbO7uP386UUqQ5y4LXDsXgmvdA7Kmvs5xtEm/oFznamyPWimjzzEhHd9l2zLRf2W5NMIY/kiy+C4Ixpz6DDoz7iFRoqM7qYnGo3MEwGhWLs9Qi7MeioHsUMCxN6Ph5VJwHrqY3TbLBSxMtc5FVxAIc1YBJMCCdszi/jlZq6yzf5WHO/boiGgm5q7n/xlK0Mc8AORjWNmDkr4/8O/7/x+wD/FzHpL6fYfBH2X4xgswmw9KP0fUB3YzxWvv0zgz6ViS1pkh2bXwsRnFq/mMjFGcmOOom0iSKhcDhZjjLLthTlGN6y99TpaQY0bjWw0fOPE7yoR6a0IJkfovQHdxJx0T6NP1s/h2yV93fc66MrCS98FMcEw+8vv
  template:
    metadata:
      name: victoriametrics-auth
      namespace: external
