apiVersion: v1
kind: PersistentVolume
metadata:
  name: phis-standard-pihole
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: phis1#standard#pihole
    volumeAttributes:
      server: 192.168.1.212
      share: /media/storage/standard/pihole

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phis-standard-pihole
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: phis-standard-pihole
  storageClassName: nfs-csi
