apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /media/storage/k8s-data/pihole
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - phis1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phis-standard-pihole
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pihole-pv
