---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: networking
spec:
  encryptedData:
    PIHOLE_PASSWORD: AgAkoJSzEajLG4ES4ju/WZWXV8tnjgGvla3YQu81X7gKYSivjlgFhsdiiMdR1b51RYC7VRUW6aPP7e0WEVj+Zx/KIqZQSuoJCsXHFDbQHwvgocP1B+AxJOp3QpOREFytouj9+Kh8Jhsq+Qs/02K4Qi04yjUKnvYuntwzx5u0Cf6PoJFuyD+ARwisqUahsFgu47ix8TVwxapK2JoZAzO9iIIXxcLVbtAWmFQpX+elDMAczGHfLlYxrRFAaS7PF8l1xHQaN6qTANy60ENxeQ4XGNul/Fi0b6LmxQr66+x5lZ0i0st7ipeoUjVpovhnwQDNMPCFHhr9SAYyOVFehd68nbpDCn9ylv9Tq6b47ZdvVizml04qgQatLGC4grwuAG15KaRyNftgBOUzAOBH8g67GIIaO7Ck/xCdAclG95Ik15cUjNW6g4Ceaab6bRLkrVRi+b2QmPWSLQNxSz6eQAULibwg7qa4qNIvud+wY6rF1jeqt5P1TE/OfIoUMTxEHKb6RtblfNT9bB7UOl2QwLHP/aBNqgvuBOWQ/aWGt/Mi+qS9lwYFtO6yJwsVal5sXNHkVSAsaFFEm+X1Vx7TMsIbbLEWktGIaAGCuCjupMBx1hq/yUfeh7UYye/HcJ9qTWKp+GmMo332som8KcwD15Scwuf7Xj2RJpUFtO61Go/lMe+4E5/7p8JROhbTGq90C3PeU1HCHPxEQ2/Ll4UIoNVmOM5GbZtzQRopBw==
  template:
    metadata:
      name: pihole-secrets
      namespace: networking
