---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: networking
spec:
  encryptedData:
    PIHOLE_PASSWORD: AgBTcHHeG/lUyXs80QCe+hxnoP9KOSNDU8UaiA/96chXIuGjeRRZlnjCpHi/Orb5AJ4Eo9iGfOLK7uaD8ks3Ubd0ihjnww0bwNBFsZgNxkvem62xX3a8aa9lAVMJKkJXYH0Ul4kruy+KhzNRfE1OYRag/0hkeXWi5zxfTaMn6RQuUxOEoujYkHYcugFmZDzqWx9zBAuQIEvCKj+LdB96SAFfNKFeId9zDPJchERw7hKfUKkNurgsv5MDY1fTL5zOwsE7M1JWqLrz3jqODEim86LX7Xwi3sIe6eDp52R+1+0aAhHIzJHczF2JxFLU8cdkCRdeCcveRJaMH5tKyxtGqwW89kYq1mBtN8WHp9sHh1V/N9pBa9LPDX5oyoWsbFFNf+TleUclJ9EIY8Bz6yw+RXuwbPl0uKjWnN49znsXxQAFa+UrxVmnyAsRn0CU27lLlDwJlbyj4WvxPl+BF+V9D/CWza9tobre1/Z3m1F9s2X3xr3Zhbu8mtetdylZved/j6GvBt+xttJAElI3wUnsq411RrzMJ0/paU/H4MlA70J3k5HWbe3jFgHgB47g4bWSJpeZQDSbzAtZyrUu6G4BgybHFSYfLYA+Ofowi/ihzRsBivONaMH8oPqg36it5TS+X1A3WrE9epMUZ0abwsc5TDSaYnkBLAbI9mQEcNoTrSpKB8HiLPkGB/A67cDWTOg6CXCYv0hwvrQcAqkNuEfgaY1xvX55fL35Ow==
  template:
    metadata:
      name: pihole-secrets
      namespace: networking
