apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: networking
  labels:
    app.kubernetes.io/name: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.220
  allocateLoadBalancerNodePorts: false
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: pihole-http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: pihole-https
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    app.kubernetes.io/name: pihole
