---
kind: PersistentVolume
apiVersion: v1
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: phis-standard-psql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: phis1#standard#psql
    volumeAttributes:
      server: 192.168.1.212
      share: /media/storage/standard/psql

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: phis-standard-psql
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: phis-standard-psql
  storageClassName: nfs-csi

---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: default
  labels:
    app.kubernetes.io/name: postgres
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: psql-port
  selector:
    app.kubernetes.io/name: postgres

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: phis-standard-psql
      containers:
        - name: postgres
          image: 'postgres:17'
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: 'America/Denver'
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          ports:
            - name: psql-port
              containerPort: 5432
              protocol: TCP
