---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets
  namespace: default
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAIVd1P2F+Q5AVoH+cBgl5hGACkJQZyTaX65NNVn9YF+tLr+sgTQnJsWQoAZ3vcpPnfo5hd2YJ8oulp8G8TVBqN157G/h7/5mcmow6ScQMft9LB2EctozMRQeekg2Zy1AP1VvmTasN1DRBip0AcFMEPXRUvALvgXR3YtL/JXKUzjBrx2FHUrQbDFm4k2GDt8DULd/o5GJzSzExuEFz2WAJnNe2pb8gmJEbjpZQv7hprlga1pf/ko5ovvmELRHkHPqgy2aFHREmH9X/42mxV+28SJaBCkL94cX3QofaWznHc9LJ7qVb2n/DKM886iLD2FG1bXTBhZg0lKm3lHZ5ZPAHCWo2ZTqN37MLl1SxxyMULxYU6EwUjERFmNxNElRy99+vw3CI/g3oL6DDbR7N5c98hfiZXh4rsUmHDt0hxa39gaFHH8HL7BWmSmlvG8nfOm8GbYvRQ0PWQicTvLs9HOXK7kNeqjhUlTx4Kt1TXUqXbkS2SSDnDh0jj20geKurNlWDnF6uFvYESSSYNhNL1E/Bm2X0l7or8cLrvMJLXtGB4xH9zYGbxU+IAqRocppIpFmqmEcB4dnru/nyeofScHdeqA1W3Zli5KIEt3q1bfnx7WBB+nGRVUdGYbiSuK8jGKlfwID2jW8zV8+VnJrGVHd8fctB+W7Lxcj1aFjDgeptAAlWRXpwHK71hpfqVd7O1W7jQkcop8uMniawWk/uTzrtl0EGt14NQLa9tohz0zeo4yCFfx+5DX1btN2G09JS8XF/R+6WocBTnCVnW+EnZFd5ylaYMBA4QFNj6lDG8LqZ4i9mghaNUXFG5jOfsQ37jlsHYoRT3uEKgBkZk+mGGhzy0qmbX+21FiJFpCu7frtCwMpRIIr/40IrKAxl/moKAsO51tuZebl+W0tpT+eijxCEHDap9gaTCCjtxXHuoLfd3aRJOcEHSffMa
  template:
    metadata:
      name: secrets
      namespace: default
    type: Opaque
