apiVersion: v1
kind: PersistentVolume
metadata:
  name: phis-standard-nginx
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: phis1#standard#nginx
    volumeAttributes:
      server: 192.168.1.212
      share: /media/storage/standard/nginx

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phis-standard-nginx
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeName: phis-standard-nginx
  storageClassName: nfs-csi
