# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: homeassist-data
#   namespace: network
#   labels:
#     io.portainer.kubernetes.application.stack: homeassist
#     app.kubernetes.io/name: homeassist
#     app.kubernetes.io/type: local
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 5Gi
#   local:
#     path: /var/lib/homeassist
#   persistentVolumeReclaimPolicy: Retain
#   accessModes:
#     - ReadWriteMany
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#           - key: app
#             operator: In
#             values:
#               - homeassist

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassist-claim
  namespace: network
  labels:
    io.portainer.kubernetes.application.stack: homeassist
    app.kubernetes.io/name: homeassist
spec:
  # volumeName: homeassist-data
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
kind: Service
apiVersion: v1
metadata:
  name: homeassist
  namespace: network
  labels:
    io.portainer.kubernetes.application.stack: homeassist
    app.kubernetes.io/name: homeassist
spec:
  type: LoadBalancer
  selector:
    app: homeassist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
  selector:
    app: homeassist

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: homeassist
  namespace: network
  # annotations:
  #   reloader.stakater.com/auto: "true"
  labels:
    io.portainer.kubernetes.application.stack: homeassist
    app.kubernetes.io/name: homeassist
    app.kubernetes.io/version: "2024.07.0"
spec:
  selector:
    matchLabels:
      app: homeassist
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homeassist
      annotations:
        deploy-date: "deploy-date-value"
    spec:
      volumes:
        - name: homeassist-content
          persistentVolumeClaim:
            claimName: homeassist-claim
      containers:
        - name: homeassist
          image: homeassistant/home-assistant:2025.1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8123
          env:
            - name: TZ
              value: "America/Denver"
          volumeMounts:
            - mountPath: /config
              name: homeassist-content
      hostNetwork: true