apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassist-data
  namespace: apps
  labels:
    app.kubernetes.io/name: homeassist
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
