apiVersion: v1
kind: Service
metadata:
  name: homeassist
  namespace: apps
  labels:
    app.kubernetes.io/name: homeassist
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
  selector:
    app.kubernetes.io/name: homeassist
