apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: networking
  labels:
    app.kubernetes.io/name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.227
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: nginx
